name: hms_cloud

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  cl:
    git: git@repo.centryl.org:centryl/cl.git
  cl_base:
    git: git@repo.centryl.org:centryl/cl_base.git
  pdf:
    git: git@repo.centryl.org:centryl/pdf.git
  auth:
    path: modules/auth
  project:
    path: modules/project
  local:
    path: modules/local

dev_dependencies:
  build_runner: ^1.10.1
  build_web_compilers: ^2.11.0
