name: auth

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  cryptography: ^1.4.1
  dbcrypt: ^1.0.0
  cl:
    git: git@repo.centryl.org:centryl/cl.git
  cl_base:
    git: git@repo.centryl.org:centryl/cl_base.git
  icon:
    path: ../icon

dev_dependencies:
  test: ^1.9.4
  build_runner: ^1.7.2