name: project

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  dbcrypt: ^1.0.0
  cl:
    git: git@repo.centryl.org:centryl/cl.git
  cl_base:
    git: git@repo.centryl.org:centryl/cl_base.git
  cl_local:
    git: git@repo.centryl.org:centryl/cl_local.git
  pdf:
    git: git@repo.centryl.org:centryl/pdf.git
  icon:
    path: ../icon
  auth:
    path: ../auth
  local:
    path: ../local

dev_dependencies:
  test: ^1.9.4
  build_runner: ^1.7.2